#!/bin/bash
# Terrain Editor Fork - Development Environment Setup (macOS/Linux)
# Run once per machine: ./setup.sh
#
# What this does:
#   1. Installs required VS Code/Cursor extensions
#   2. Installs Rojo/Selene/StyLua via Aftman (if needed)
#   3. Creates .vscode/settings.json with YOUR machine's paths
#   4. Installs Wally packages (if wally.toml exists)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "=== Terrain Editor Fork Setup ==="

# Required extensions - mandatory, not recommendations
REQUIRED_EXTENSIONS=(
    "JohnnyMorganz.luau-lsp"   # Luau language support
)

# Extensions to uninstall (cause conflicts)
CONFLICTING_EXTENSIONS=(
    "Nightrains.robloxlsp"     # Legacy - conflicts with luau-lsp
)

# Find editor CLI (cursor or code)
find_editor_cli() {
    if command -v cursor &> /dev/null; then
        echo "cursor"
    elif command -v code &> /dev/null; then
        echo "code"
    else
        echo ""
    fi
}

# Find Rojo
find_rojo() {
    if command -v rojo &> /dev/null; then
        command -v rojo
        return
    fi
    
    local aftman_rojo="$HOME/.aftman/bin/rojo"
    if [[ -x "$aftman_rojo" ]]; then
        echo "$aftman_rojo"
        return
    fi
    
    local paths=(
        "/usr/local/bin/rojo"
        "$HOME/.cargo/bin/rojo"
    )
    for path in "${paths[@]}"; do
        if [[ -x "$path" ]]; then
            echo "$path"
            return
        fi
    done
    
    echo ""
}

# Step 1: Install required extensions
echo ""
echo "[1/4] Installing required extensions..."

EDITOR_CLI=$(find_editor_cli)
if [[ -n "$EDITOR_CLI" ]]; then
    # Remove conflicting extensions
    for ext in "${CONFLICTING_EXTENSIONS[@]}"; do
        if "$EDITOR_CLI" --list-extensions 2>/dev/null | grep -q "^${ext}$"; then
            echo "  Removing conflicting: $ext"
            "$EDITOR_CLI" --uninstall-extension "$ext" 2>/dev/null || true
        fi
    done
    
    # Install required extensions
    for ext in "${REQUIRED_EXTENSIONS[@]}"; do
        if "$EDITOR_CLI" --list-extensions 2>/dev/null | grep -q "^${ext}$"; then
            echo "  Already installed: $ext"
        else
            echo "  Installing: $ext"
            "$EDITOR_CLI" --install-extension "$ext" --force 2>/dev/null || true
            echo "  Installed: $ext"
        fi
    done
else
    echo "  VS Code/Cursor CLI not found. Install extensions manually:"
    for ext in "${REQUIRED_EXTENSIONS[@]}"; do
        echo "    - $ext"
    done
fi

# Step 2: Ensure Aftman tools are installed
echo ""
echo "[2/4] Checking toolchain..."

ROJO_PATH=$(find_rojo)

if [[ -z "$ROJO_PATH" ]]; then
    echo "  Rojo not found. Installing via Aftman..."
    
    if ! command -v aftman &> /dev/null; then
        echo ""
        echo "  Aftman is not installed. Install it first:"
        echo "    cargo install aftman"
        echo "  Or see: https://github.com/LPGhatguy/aftman#installation"
        exit 1
    fi
    
    cd "$SCRIPT_DIR"
    aftman install
    
    ROJO_PATH=$(find_rojo)
    if [[ -z "$ROJO_PATH" ]]; then
        echo "  Failed to install Rojo. Check aftman.toml"
        exit 1
    fi
fi

echo "  Rojo: $ROJO_PATH"
"$ROJO_PATH" --version

# Step 3: Create .vscode/settings.json
echo ""
echo "[3/4] Configuring editor settings..."

VSCODE_DIR="$SCRIPT_DIR/.vscode"
SETTINGS_FILE="$VSCODE_DIR/settings.json"

mkdir -p "$VSCODE_DIR"

cat > "$SETTINGS_FILE" << EOF
{
    "// NOTE": "Machine-specific settings - auto-generated by setup.sh",
    "// This file is in .gitignore. Safe to customize for your machine.": null,

    "luau-lsp.sourcemap.rojoPath": "$ROJO_PATH",
    "robloxLsp.enable": false,
    "discord.enabled": false
}
EOF

echo "  Created: $SETTINGS_FILE"

# Step 4: Install Wally packages (optional)
echo ""
echo "[4/4] Installing dependencies..."

if [[ -f "$SCRIPT_DIR/wally.toml" ]]; then
    WALLY_PATH="$HOME/.aftman/bin/wally"
    if ! [[ -x "$WALLY_PATH" ]]; then
        WALLY_PATH=$(command -v wally 2>/dev/null || echo "")
    fi
    
    if [[ -n "$WALLY_PATH" && -x "$WALLY_PATH" ]]; then
        cd "$SCRIPT_DIR"
        "$WALLY_PATH" install
        echo "  Wally packages installed"
    else
        echo "  Wally not found (skipping)"
    fi
else
    echo "  No wally.toml (skipping)"
fi

# Done!
echo ""
echo "=== Setup Complete! ==="
echo ""
echo "Your environment is configured. Next steps:"
echo ""
echo "  1. Reload editor window (Cmd+Shift+P -> \"Reload Window\")"
echo "  2. Start Rojo:  rojo serve"
echo "  3. Connect in Studio and start editing!"
echo ""

