# Terrain Editor Fork - Development Environment Setup (Windows)
# Run once per machine: .\setup.ps1
#
# What this does:
#   1. Installs required VS Code/Cursor extensions
#   2. Installs Rojo/Selene/StyLua via Aftman (if needed)
#   3. Creates .vscode/settings.json with YOUR machine's paths
#   4. Installs Wally packages (if wally.toml exists)

$ErrorActionPreference = "Stop"

Write-Host "`n=== Terrain Editor Fork Setup ===" -ForegroundColor Cyan

# Required extensions - these are mandatory, not recommendations
$requiredExtensions = @(
    "JohnnyMorganz.luau-lsp"   # Luau language support (autocomplete, types, go-to-definition)
)

# Extensions to uninstall (cause conflicts or problems)
$conflictingExtensions = @(
    "Nightrains.robloxlsp"     # Legacy - conflicts with luau-lsp
)

# Find the editor CLI (code or cursor)
function Find-EditorCli {
    # Check for Cursor first (since we're likely in Cursor)
    $cursor = Get-Command cursor -ErrorAction SilentlyContinue
    if ($cursor) { return "cursor" }
    
    # Fall back to VS Code
    $code = Get-Command code -ErrorAction SilentlyContinue
    if ($code) { return "code" }
    
    return $null
}

# Find Rojo - check multiple possible locations
function Find-Rojo {
    $onPath = Get-Command rojo -ErrorAction SilentlyContinue
    if ($onPath) { return $onPath.Source }
    
    $aftmanRojo = "$env:USERPROFILE\.aftman\bin\rojo.exe"
    if (Test-Path $aftmanRojo) { return $aftmanRojo }
    
    $commonPaths = @(
        "$env:LOCALAPPDATA\Programs\rojo\rojo.exe",
        "$env:ProgramFiles\rojo\rojo.exe",
        "C:\rojo\rojo.exe"
    )
    foreach ($path in $commonPaths) {
        if (Test-Path $path) { return $path }
    }
    
    return $null
}

# Step 1: Install required extensions
Write-Host "`n[1/4] Installing required extensions..." -ForegroundColor Yellow

$editorCli = Find-EditorCli
if ($editorCli) {
    # Remove conflicting extensions first
    foreach ($ext in $conflictingExtensions) {
        $installed = & $editorCli --list-extensions 2>$null | Select-String -Pattern "^$ext$" -Quiet
        if ($installed) {
            Write-Host "  Removing conflicting: $ext" -ForegroundColor Gray
            & $editorCli --uninstall-extension $ext 2>$null | Out-Null
        }
    }
    
    # Install required extensions
    foreach ($ext in $requiredExtensions) {
        $installed = & $editorCli --list-extensions 2>$null | Select-String -Pattern "^$ext$" -Quiet
        if ($installed) {
            Write-Host "  Already installed: $ext" -ForegroundColor Green
        } else {
            Write-Host "  Installing: $ext" -ForegroundColor Yellow
            & $editorCli --install-extension $ext --force 2>$null | Out-Null
            Write-Host "  Installed: $ext" -ForegroundColor Green
        }
    }
} else {
    Write-Host "  VS Code/Cursor CLI not found. Install extensions manually:" -ForegroundColor Red
    foreach ($ext in $requiredExtensions) {
        Write-Host "    - $ext" -ForegroundColor White
    }
}

# Step 2: Ensure Aftman tools are installed
Write-Host "`n[2/4] Checking toolchain..." -ForegroundColor Yellow

$rojoPath = Find-Rojo

if (!$rojoPath) {
    Write-Host "  Rojo not found. Installing via Aftman..." -ForegroundColor Yellow
    
    $aftman = Get-Command aftman -ErrorAction SilentlyContinue
    if (!$aftman) {
        Write-Host "`n  Aftman is not installed. Install it first:" -ForegroundColor Red
        Write-Host "    winget install LPGhatguy.Aftman" -ForegroundColor White
        Write-Host "  Or see: https://github.com/LPGhatguy/aftman#installation" -ForegroundColor Gray
        exit 1
    }
    
    Push-Location $PSScriptRoot
    aftman install
    Pop-Location
    
    $rojoPath = Find-Rojo
    if (!$rojoPath) {
        Write-Host "  Failed to install Rojo. Check aftman.toml" -ForegroundColor Red
        exit 1
    }
}

Write-Host "  Rojo: $rojoPath" -ForegroundColor Green
& $rojoPath --version

# Step 3: Create .vscode/settings.json
Write-Host "`n[3/4] Configuring editor settings..." -ForegroundColor Yellow

$vscodeDir = "$PSScriptRoot\.vscode"
$settingsFile = "$vscodeDir\settings.json"

if (!(Test-Path $vscodeDir)) {
    New-Item -ItemType Directory -Path $vscodeDir | Out-Null
}

$escapedPath = $rojoPath.Replace("\", "\\")
$settingsContent = @"
{
    "// NOTE": "Machine-specific settings - auto-generated by setup.ps1",
    "// This file is in .gitignore. Safe to customize for your machine.": null,

    "luau-lsp.sourcemap.rojoPath": "$escapedPath",
    "robloxLsp.enable": false,
    "discord.enabled": false
}
"@

$settingsContent | Out-File -FilePath $settingsFile -Encoding utf8 -NoNewline
Write-Host "  Created: $settingsFile" -ForegroundColor Green

# Step 4: Install Wally packages (optional)
Write-Host "`n[4/4] Installing dependencies..." -ForegroundColor Yellow

$wallyToml = "$PSScriptRoot\wally.toml"
if (Test-Path $wallyToml) {
    $wallyPath = "$env:USERPROFILE\.aftman\bin\wally.exe"
    if (!(Test-Path $wallyPath)) {
        $wallyPath = (Get-Command wally -ErrorAction SilentlyContinue).Source
    }
    
    if ($wallyPath -and (Test-Path $wallyPath)) {
        Push-Location $PSScriptRoot
        & $wallyPath install
        Pop-Location
        Write-Host "  Wally packages installed" -ForegroundColor Green
    } else {
        Write-Host "  Wally not found (skipping)" -ForegroundColor Gray
    }
} else {
    Write-Host "  No wally.toml (skipping)" -ForegroundColor Gray
}

# Done!
Write-Host "`n=== Setup Complete! ===" -ForegroundColor Cyan
Write-Host @"

Your environment is configured. Next steps:

  1. Reload editor window (Ctrl+Shift+P -> "Reload Window")
  2. Start Rojo:  rojo serve
  3. Connect in Studio and start editing!

"@ -ForegroundColor White

